### ISSUE TITLE
[tree widget] all sv's are unavailable when there are no places selected

### ISSUE THREAD

**Issue by beets** [datacommonsorg/website#1004]
To reproduce:
https://autopush.datacommons.org/tools/timeline
- start by navigating the tree widget (before selecting a place). note that all sv's are grayed out

Expected:
- all sv's are available until a place is selected

We'll also need to handle the case where a sv is selected, then a place for which the sv is unavailable. In that case, perhaps an error dialog saying Data is unavailable for the place - please choose another place or variable. 

cc @shifucun

**Comment by chejennifer** [comment]
I also noticed that if we open up a section before selecting a place, then select a place, the svs remain grayed out. I will also look into that while working on this bug.

**Comment by shifucun** [comment]
Sent a fix here https://github.com/datacommonsorg/mixer/pull/571
