### ISSUE TITLE
[tree widget] some intermediate nodes are marked unavailable but highlighted

### ISSUE THREAD

**Issue by beets** [datacommonsorg/website#1007]
On autopush:
https://autopush.datacommons.org/tools/timeline#place=geoId%2F0655282%2CgeoId%2F0620956&pc=0&statsVar=Median_Income_Person__Count_Person_USCitizenBornAbroadOfAmericanParents&chart=%7B%22count%22%3Afalse%7D

Note that in the path: Demographics > Immigration and Citizenship > Citizenship Status
--> Immigration and Citizenship is part of the path, but is grayed out

![image](https://user-images.githubusercontent.com/6052978/124010211-669e4380-d993-11eb-95b0-b4d0571a5a19.png)

**Comment by beets** [comment]
Possibly related, seeing this in scatter as well ("covid 19 mobility trend of residence" chosen via search):
https://autopush.datacommons.org/tools/scatter#%26svx%3DCount_Person_AsianAlone%26svy%3Ddc%2F7fmnve6yyc508%26pcy%3D1%26epd%3DgeoId%2F06%26epn%3DCalifornia%26ept%3DCounty
![image](https://user-images.githubusercontent.com/6052978/124039171-3f596d80-d9b7-11eb-95ff-4c65f01d5d8f.png)

**Comment by chejennifer** [comment]
This bug was due to data problems which were fixed with the new cache build.
