### ISSUE TITLE
[tree widget] search / filter updates

### ISSUE THREAD

**Issue by beets** [datacommonsorg/website#1022]
- remove [x] when there is no input
- change the text from "filter statistical variables" to "search variables"
- consider removing the "select variables" header

**Comment by chejennifer** [comment]
I think it looks a little bare without the header?
<img width="410" alt="Screen Shot 2021-07-13 at 3 52 03 PM" src="https://user-images.githubusercontent.com/69875368/125535286-1158a92c-87cb-422b-90e9-84b25e0c2c33.png">

**Comment by chejennifer** [comment]
or if we move the (i) lower, it doesn't look as bare without the header?
<img width="464" alt="Screen Shot 2021-07-13 at 4 10 26 PM" src="https://user-images.githubusercontent.com/69875368/125536635-62c788e4-bc04-4fb5-8f48-088c23a51ce7.png">

**Comment by beets** [comment]
explored this a bit in #1054 

i agree that it looks bare without the text and perhaps the solution is to just reduce the font size of the label. will close this out, and we'll solve it together with the other control in 1054.
