### ISSUE TITLE
[timeline] ordering of graphs wrt tree widget

### ISSUE THREAD

**Issue by beets** [datacommonsorg/website#1026]
From Ajai:

![image](https://user-images.githubusercontent.com/6052978/125523563-d924a00c-d57b-4b0d-ab6e-b558acfa8a6e.png)

The ordering of the charts seems arbitrary - if they are sorted, it should be on something visible on the screen. Could we add each new chart to the top? That would also solve the confusion of charts "not appearing" on the screen, but are in the scroll area. Thoughts?

**Comment by chejennifer** [comment]
Adding each new chart to the top makes sense to me. I guess when user navigates to the page via URL, we would show the charts in the order of the stat vars in the URL?
