### ISSUE TITLE
[timeline] Line not showing up for some charts

### ISSUE THREAD

**Issue by chejennifer** [datacommonsorg/website#1031]
https://autopush.datacommons.org/tools/timeline#statsVar=dc%2Fnm9hcklgg5zb3__Count_Person_Employed&place=nuts%2FES61%2CgeoId%2F56
- the line for purple employed population doesn't show up although when hovering, we can see that there are data points for the purple employed population.

**Comment by beets** [comment]
another case: single points are also not visible
https://autopush.datacommons.org/tools/timeline#place=geoId%2F06&statsVar=LifeExpectancy_Person&chart=%7B%22genderIncomeInequality%22%3Afalse%7D
