### ISSUE TITLE
[timeline] Should tooltip labeling be consistent with legend?

### ISSUE THREAD

**Issue by chejennifer** [datacommonsorg/website#1033]
go to: https://autopush.datacommons.org/tools/timeline#statsVar=dc%2Fhj65vwnt5csr7__dc%2Fyt1fm72s1y7b7__dc%2F0sd3x3bb4qet5__dc%2Fj4mzcc63n5zq5__dc%2F56jhsezrzl049__dc%2Fggx918j9p5tnf__dc%2F8rw47nf3ngle7__dc%2Fhplj99j7mbfsh__dc%2Fksmx7fwfkm8lb__dc%2F6706lc55kg5d__dc%2Fqcpg8c533syd6__dc%2Fzv26z833d7g3c__dc%2Fkz49wc5n3lhpd&place=country%2FUSA&chart=%7B%22count%22%3Afalse%7D

- The tooltip uses the dcid as labels while the legend and chips use the stat var name. Should we be consistent and use stat var names everywhere?

**Comment by beets** [comment]
+1 we should absolutely use sv names everywhere
