### ISSUE TITLE
[tree widget] expand the tree for preselected vars when on page load

### ISSUE THREAD

**Issue by beets** [datacommonsorg/website#1036]
when clicking on a link like this:
https://autopush.datacommons.org/tools/timeline#place=geoId%2F06%2CgeoId%2F26&statsVar=Annual_Consumption_Coal_ElectricPower&chart=%7B%22consumption%22%3Afalse%2C%22cost%22%3Afalse%2C%22heatContent%22%3Afalse%7D

the current behavior is to stay collapsed, like this:
![image](https://user-images.githubusercontent.com/6052978/125527842-8cf3b77f-fdbe-4453-bf2c-ea469e792433.png)

should we expand so it starts like this:
![image](https://user-images.githubusercontent.com/6052978/125528026-ee53bd3d-e53a-43b6-bc54-d84a419c1551.png)

thoughts?

**Comment by chejennifer** [comment]
I think it depends on if it's more likely for user to want to be in expanded form or not. 

I can see use cases for both. 
- if user wants to explore stat vars similar to the ones already selected, having the page open with menu expanded form will make it a lot easier for users to get to the sections of the selected stat vars. 
- If user just wants to look at what other stat vars are available in the menu, it might be easier for them if the menu isn't already expanded.

**Comment by beets** [comment]
i think most often, the user will want to explore neighboring / related vars. it'll also help to "teach" about the tree widget, and it's existing behavior in the pv tree. the difference is now the tree is much richer so it could be a little overwhelming, but i think the context is still useful

**Comment by beets** [comment]
i think that will be rare in actual usage though -- most often, the stat vars will be related. at least it'll still show the context (part of the thinking here is our sv names do not always include the context, so this will help with that too).

to help, perhaps we can expand only if all the children are under a single sv vertical?

**Comment by shifucun** [comment]
We should at least expand for map tool.
