### ISSUE TITLE
[tree widget] Add mechanism to blocklist statvar groups

### ISSUE THREAD

**Issue by chejennifer** [datacommonsorg/website#1041]
- add mechanism to blacklist stat var groups so that they don't show up in the tree widget. (only for prod)

**Comment by pradh** [comment]
Could you add some context/examples for ones that we'd like to blocklist?

**Comment by chejennifer** [comment]
When we were looking at the tree widget yesterday, we saw that there were what looked like duplicate stat var groups. However, I don't actually have the list of groups we want to blocklist. We want to be able to only blocklist in prod, so that we can still debug what's actually going on using autopush/staging.

**Comment by shifucun** [comment]
One example is we have many duplicate names in the NAICS. Before that's cleaned up, we want to block the industries subtree.
