### ISSUE TITLE
[tree widget] add toggle for unavailable vars

### ISSUE THREAD

**Issue by beets** [datacommonsorg/website#1054]

**Comment by beets** [comment]
here's an option (tried also putting it at the bottom / without a button, but that didn't look good)

![image](https://user-images.githubusercontent.com/6052978/125870393-1c3967fc-b5c2-4472-a4fb-e3941e7b5fb6.png)

the other thing to consider is, i think it will be good to have a similar button to clear search results (the x is quite hidden). in that case, we'd replace the button with one that says "clear search result"

wdyt?

**Comment by beets** [comment]
another option:
![image](https://user-images.githubusercontent.com/6052978/125871206-7784f65b-d0d4-4aa0-8927-5a66117efae4.png)

**Comment by shifucun** [comment]
> another option:
> ![image](https://user-images.githubusercontent.com/6052978/125871206-7784f65b-d0d4-4aa0-8927-5a66117efae4.png)

I like this option, looks cleaner. Also would be nice to indicate "unavailable" is the "grayed" stat vars since users might not link them together at first glance.

**Comment by chejennifer** [comment]
or something like this if we want the clear results?
<img width="522" alt="Screen Shot 2021-07-19 at 10 43 27 PM" src="https://user-images.githubusercontent.com/69875368/126267912-1e81331b-a8f1-4529-b537-a354c94ecf68.png">

**Comment by beets** [comment]
show all | show available
try putting it at the bottom - will post a screenshot

**Comment by beets** [comment]
the toggle on top:
![image](https://user-images.githubusercontent.com/6052978/126699494-2f66a87b-6354-4dde-9d8a-482cbde84619.png)
(with some margin cleanup):
![image](https://user-images.githubusercontent.com/6052978/126700152-20f7ea7f-0202-46cb-a9c0-87445a3c2c1d.png)

or below, with / without the scrollbars
![image](https://user-images.githubusercontent.com/6052978/126699570-7a38e70b-51eb-4564-9b7d-65d9458c5733.png)
![image](https://user-images.githubusercontent.com/6052978/126698588-e3e5d779-f480-41ee-9ce9-ef582f30e16a.png)

(with margin cleanup):
![image](https://user-images.githubusercontent.com/6052978/126700460-e894f680-2094-462e-adc5-af29bd8d7c47.png)
![image](https://user-images.githubusercontent.com/6052978/126700636-c66565d8-6e97-4c83-a16a-dcb6c433266c.png)

i'm leaning with putting it below, with some margin cleanup, wdyt?

**Comment by chejennifer** [comment]
I like the toggle on top where it's on the same line as the info tooltip.
I think having the horizontal scroll separating the toggle from the rest of the hierarchy looks a little odd

Also, when the toggle is off, will the label change? or will the label always be "Show all statistical variables"?

**Comment by beets** [comment]
Typically, we shouldn't have to change the label of a toggle, but we can use color to make it clear which state is "on" (used --dc-blue and --dc-gray-lite)

![image](https://user-images.githubusercontent.com/6052978/126705942-f5e82780-8f8f-4c76-b8a2-ec7ae28dccd7.png)

![image](https://user-images.githubusercontent.com/6052978/126706127-01b82d97-319b-4718-9fa3-befbd6b8f8c2.png)

**Comment by beets** [comment]
Fixed in #1073
