### ISSUE TITLE
[Feedback] Consider UI Treatment for admin area containment info

### ISSUE THREAD

**Issue by tjann** [datacommonsorg/website#114]
### Feedback
Right now, browser randomly selects one of multiple typeOf to display. For states in the US, some are under "contained in place of Admin Area1", others are under "contained in place of State", yet others are under. "contained in place of Admin Area"

### About
URL: https://browser.datacommons.org/kg?dcid=country/USA

### Expected behavior
All under "State" or "AdminArea1", etc.

### Screenshots
If applicable, add screenshots to help explain the issue or suggestion.

![image](https://user-images.githubusercontent.com/18621425/87840632-92ddb480-c855-11ea-9636-177ad358cfbe.png)
![image](https://user-images.githubusercontent.com/18621425/87840640-9709d200-c855-11ea-9fb5-c1d9f9941138.png)

**Comment by pradh** [comment]
+1 (https://screenshot.googleplex.com/QSP1sxLv0Ao)

**Comment by beets** [comment]
Reopening since there's ongoing discussion in #163 about ranking the contained types.

**Comment by beets** [comment]
fixed with the new browser
