### ISSUE TITLE
[BUG] Document and improve long single-node chains in SV hierarchy

### ISSUE THREAD

**Issue by pradh** [datacommonsorg/website#1182]
![NotInsuredProblem](https://user-images.githubusercontent.com/4375037/137382871-6edf52f6-d074-415f-8238-e17d9c28142e.png)

This one seems like a missing DPV issue

**Comment by beets** [comment]
In the interim, should we bring back the change to "autoclick/expand" these chains

**Comment by beets** [comment]
we brought back auto-expand.. and we've reduced these occurences.
