### ISSUE TITLE
[BUG] Low-pri: NUTS regions only in EU countries

### ISSUE THREAD

**Issue by pradh** [datacommonsorg/website#1232]
![Screen Shot 2021-10-27 at 11 00 37 AM](https://user-images.githubusercontent.com/4375037/139120933-d07f233b-c204-421d-8a05-74d180c96c7f.png)

**Comment by pradh** [comment]
This works well on Map tool:

![Screen Shot 2021-10-29 at 4 58 46 PM](https://user-images.githubusercontent.com/4375037/139512621-f754be63-6cf1-40ad-bf68-7cb96c76376e.png)

**Comment by beets** [comment]
Best solution might be to come up with a config of containment types & equivalence -- Eurostat NUTS is not a common term, so it might be nicer to say instead "Country" "Provinces / States" etc

**Comment by beets** [comment]
fixed
