### ISSUE TITLE
[Map] Inconsistent place highlight/linking

### ISSUE THREAD

**Issue by pradh** [datacommonsorg/website#1259]
For example: https://datacommons.org/tools/map#%26sv%3Deia%2FINTL.4008-8-MMTCD.A%26pc%3D0%26denom%3DCount_Person%26pd%3DEarth%26pn%3DEarth%26pt%3DPlace%26ept%3DCountry (screenshot below)

1. Hovering over certain map places shows yellow boundary, while others don't
2. Only certain places in the rank list are hyperlinks
3. Like (1), hovering over some hyperlinked places show highlights, but some don't (e.g., Saint Helena)
4. Clicking on most throws error (in this case the SV is missing at State level)

![image](https://user-images.githubusercontent.com/4375037/139515697-bd9d5f2b-4217-4d78-8915-697a16695780.png)

**Comment by beets** [comment]
re (1 &3): i have a pending fix in #1268 which shows that st helena is highlighted, but it's really small at that zoom level. should be a bit more visible now that the rest of the map is made transparent.

![image](https://user-images.githubusercontent.com/6052978/139790150-7ee14bc4-4287-4613-8db1-9339d0d04542.png)

(2 & 4): we do "contained in place - europe" as part of our clickability test, not checking if there is indeed data at the next zoom level. that also returns russia and st helena as clickable places, even though we don't have eurostat nuts places for those.

we could treat those clicks as zooming in to a "leaf" map page (and that would enable clicking on every country).
