### ISSUE TITLE
[BUG] countries / continents that look bad in map view

### ISSUE THREAD

**Issue by pradh** [datacommonsorg/website#1298]
* [North America](https://autopush.datacommons.org/tools/map#%26sv%3DDifferenceRelativeToBaseDate2006_Max_Temperature_RCP45%26pc%3D0%26denom%3DCount_Person%26pd%3Dnorthamerica%26pn%3DNorth%20America%26pt%3DContinent%26ept%3DCountry)
* France
* Norway
* UK
* Russia
* Portugal
* Spain (only slightly)
* ...

**Comment by pradh** [comment]
@beets fyi

**Comment by beets** [comment]
thanks - saw this which could help for some places listed.
http://geoexamples.com/d3-composite-projections/
