### ISSUE TITLE
[map] highlighting a small location looks odd

### ISSUE THREAD

**Issue by pradh** [datacommonsorg/website#1304]
![Screen Shot 2021-11-03 at 9 45 11 PM](https://user-images.githubusercontent.com/4375037/140259453-62819907-cde4-4030-9dce-fc0cf8318f12.png)

That black thing above is supposed to be the border.  Probably worth seeing if we can scale thickness depending on the zoom level or something... Low pri.

**Comment by pradh** [comment]
Also a problem when highlighting of small countries in Earth view:

![Screen Shot 2021-11-04 at 11 17 01 AM](https://user-images.githubusercontent.com/4375037/140396988-7864ae00-e39c-4dbb-8c81-db79bce167b2.png)

**Comment by beets** [comment]
For small countries in Earth view - that was the best option I could come up with that would make it visible (granted, the color is lost, but the data shows up on the tooltip).

The thick border on zoom looks really janky though
