### ISSUE TITLE
[tools] memory leaks

### ISSUE THREAD

**Issue by chejennifer** [datacommonsorg/website#1326]

**Comment by shifucun** [comment]
Error message from a localhost: http://localhost:8080/tools/scatter#%26svx%3DDifferenceRelativeToBaseDate2006_Max_Temperature_RCP45%26svy%3DPercent_Person_WithCoronaryHeartDisease%26epd%3Dcountry%2FUSA%26ept%3DCounty%26qd%3D1%26dd%3D1

Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in Chart (created by ChartLoader)
