### ISSUE TITLE
Check input error for user specified denominator in Map/Timeline tool

### ISSUE THREAD

**Issue by shifucun** [datacommonsorg/website#1333]
Should alert to user if there is no data for the input denominator stat var. It is silent now.

**Comment by beets** [comment]
here's an example of when it didn't kick in (with no warning):
https://datacommons.org/tools/map#%26sv%3DAmount_EconomicActivity_GrossDomesticProduction_Nominal_PerCapita%26pc%3D1%26denom%3D%20Amount_Emissions_CarbonDioxide_PerCapita%26pd%3DEarth%26pn%3DEarth%26pt%3DPlanet%26ept%3DCountry
