### ISSUE TITLE
[BUG] Browser legend text overlapping

### ISSUE THREAD

**Issue by tjann** [datacommonsorg/website#136]
### Describe the bug
The multi-line legends for browser charts are overlapping.

### To Reproduce
Browser: https://staging.datacommons.org/browser/country/GBR

### Expected behavior
Better handle multi-line, or adjust spacing based on elements?

### Screenshots
![image](https://user-images.githubusercontent.com/18621425/87982238-57c4c680-ca8b-11ea-95b5-cafe1301bc4f.png)

**Comment by tjann** [comment]
Reopening for this case:

![image](https://user-images.githubusercontent.com/18621425/88351712-1abb3700-cd0c-11ea-99bc-884c7b39f9da.png)

**Comment by shifucun** [comment]
The new browser does not show multiple lines in one chart and the label is moved to chart title. Closing this bug.
