### ISSUE TITLE
[BUG] Y axis scaling and labeling needs improvement

### ISSUE THREAD

**Issue by eftekhari-mhs** [datacommonsorg/website#137]
### Describe the bug
Looking at the education attainment chart we can see a couple of bugs. 
1- the y axis is all zero
2- assuming it has non zero values the relation between the lines are a bit odd, the doctorate line is the highest one (meaning that the number of people with doctorate education is higher than those with tertiary/bachelor education)

### To Reproduce
URL: https://staging.datacommons.org/browser/country/FRA
Browser: Chrome

1. Go to https://staging.datacommons.org/browser/country/FRA
2. Scroll down to 'count of Person by age,educationalAttainment'
3. Looking at the chart its Y axis is all zero

### Screenshots
https://screenshot.googleplex.com/Kq9mECjNwSm

### Additional context
The education categories are also a big concern, the doctorate line is higher than bachelor/master/or tertiary education.

**Comment by IanCostello** [comment]
Additional issue. 
The legend has a few display issues.
Long statistical variables are cut off in the legend. For small observations like fractions the values are all displayed as zero. 

To Reproduce
URL: https://staging.datacommons.org/browser/dc/p/02xgz1cylt054
Browswer: Chrome

**Comment by IanCostello** [comment]
Another example of incorrect scaling: https://staging.datacommons.org/browser/dc/p/wbk5rjtf8n5eh

**Comment by beets** [comment]
@IanCostello could you please file new bugs? they are two separate issues (legend, y-axis, x-axis, scaling)

**Comment by shifucun** [comment]
The observation here is fraction of educational attainment population rather than the raw count. The old browser does not show this and had issue with showing fractional number. This has been fixed in the new browser
![image](https://user-images.githubusercontent.com/5951856/133828821-e199b7b1-f3b7-4a52-a078-be6615455c83.png)
