### ISSUE TITLE
[BUG] 1 buggy chart (possibly missing error handling?)

### ISSUE THREAD

**Issue by tjann** [datacommonsorg/website#141]
### Describe the bug

Many bugs, but only for one chart: 

1. the orange line has no dots and has no legend.
2. there are 4 selections but only 2 lines.
3. there is no x or y axis at all.

### To Reproduce
URL: https://staging.datacommons.org/browser/nuts/AT11

### Screenshots

![image](https://user-images.githubusercontent.com/18621425/87990735-6f0ab080-ca99-11ea-87ea-33e112398817.png)

**Comment by tjann** [comment]
Update: seeing it for Edu Attainment in sub populations too

![image](https://user-images.githubusercontent.com/18621425/87992529-53a1a480-ca9d-11ea-8f24-24715beb28bb.png)

**Comment by eftekhari-mhs** [comment]
It shows the axis if we mark only one or two categories:
![image](https://user-images.githubusercontent.com/11633717/87994796-b5184200-caa2-11ea-807b-4caabe3445fb.png)

**Comment by tjann** [comment]
Fixed by #157
