### ISSUE TITLE
[BUG] missing categories (possibly missing scroll)

### ISSUE THREAD

**Issue by eftekhari-mhs** [datacommonsorg/website#142]
### Describe the bug
Some categories of employment are not appearing in the economicSector.

### To Reproduce
URL: https://staging.datacommons.org/browser/dc%2Fp%2Fgj297slbzr9j
Browser: Chrome

1. Go to 'https://staging.datacommons.org/browser/dc%2Fp%2Fgj297slbzr9j'
2. Scroll down to see 'count of Person,employment=Employed by economicSector'
3. There are about 15 NACE categories but only 7 of them are appearing

### Expected behavior
This is a screenshot from life expectancy which works fine. The user can scroll down and see all the categories.
![image](https://user-images.githubusercontent.com/11633717/87995265-daf21680-caa3-11ea-8e48-1ade9741d28b.png)
url: https://staging.datacommons.org/browser/nuts/AT11

### Screenshots
no scroll appears here
![image](https://user-images.githubusercontent.com/11633717/87995303-f65d2180-caa3-11ea-8443-bceecbe7a2bf.png)

**Comment by beets** [comment]
That's all the data there is for nuts/DEA14. Are we expecting more @eftekhari-mhs?

![image](https://user-images.githubusercontent.com/6052978/88343229-c907b200-ccf5-11ea-9a08-8ea7ccbee3d6.png)

**Comment by shifucun** [comment]
Closing this with the stat var hierarchy widget launched and showing all stat vars.
