### ISSUE TITLE
[sv widget] blank page

### ISSUE THREAD

**Issue by beets** [datacommonsorg/website#1445]
### Describe the bug
I was clicking on sv groups in the timeline tool when I the page went complete blank, just after selecting a stat var

### To Reproduce
URL:  https://autopush.datacommons.org/tools/timeline#place=geoId%2F06029%2CgeoId%2F06085&statsVar=DifferenceAcrossModels_Max_Temperature&chart=%7B%22temperature%22%3Afalse%2C%22airQualityIndex%22%3Afalse%2C%22DifferenceAcrossModels_Daily_Max_Temperature_RCP85%22%3A%7B%22pc%22%3Afalse%2C%22delta%22%3Afalse%7D%7D
Browser: chrome

It reproduces just reloading the URL

### Expected behavior
An error message, or a way to recover from the click

### Screenshots
<img width="1217" alt="image" src="https://user-images.githubusercontent.com/6052978/153703408-5592ca6f-0112-4089-9c39-3c5cdac5c5a1.png">

**Comment by chejennifer** [comment]
Do you remember the actual steps you took to get to this URL? The chart options part of the URL doesn't look like something that should be created, so I'm wondering how you got here

**Comment by beets** [comment]
I don't recall exactly. I had selected the place first, and then was selecting various stat vars in the widget hierarchy, expanding various groups.

Out of curiosity, which part of the URL is invalid?

**Comment by chejennifer** [comment]
Ok, I'll try to play around to reproduce. 

the chart options part of the URL which is set with the "chart=" param is expected to be a map of svDcid to a map of options. 
So looking at the URL you posted, in the part after "chart=",  `"temperature": false ` and `"airQualityIndex": false ` should not have been added to the URL like that.
