### ISSUE TITLE
[map] use a legend with higher contrast

### ISSUE THREAD

**Issue by beets** [datacommonsorg/website#1480]
### Describe the bug
We have many low-contrast maps. We need a legend that shows more contrast at the bottom end of the scale too (instead of fade to gray)

### To Reproduce
Low contrast:
https://datacommons.org/tools/map#%26sv%3DCount_Person_PerArea%26pc%3D0%26denom%3DCount_Person%26pd%3Dcountry%2FUSA%26ept%3DState%26domain%3D0.441%3A163.41470588235302%3A4882.537

Uneven scale, hiding the outlier in St John the Baptist Parish, LA.
https://datacommons.org/tools/map#%26sv%3DAirPollutant_Cancer_Risk%26pc%3D0%26denom%3DCount_Person%26pd%3Dcountry%2FUSA%26ept%3DCounty%26ppt%3DAirQualitySite

### Screenshots
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/6052978/157765545-74f0b062-e521-4e1a-9d66-af2731ae46bd.png">

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/6052978/157765513-f7b4b354-83ac-4a17-a121-adc343e90775.png">

### Additional context
Perhaps we can use viridis for all variables in the map tool

**Comment by sharadshriram** [comment]
Perhaps we can pick one of these diverging color bands for the plots
![image](https://user-images.githubusercontent.com/5391555/157779698-05c54e1b-79db-48e0-a458-43efb970c921.png)

The diverging color bands have one color for low and high with lighter hues for the values in between

**Comment by beets** [comment]
We don't always have diverging data -- these are useful if the range crosses 0. 

If you've time, more info on viridis:
https://cran.r-project.org/web/packages/viridis/vignettes/intro-to-viridis.html
https://www.youtube.com/watch?v=xAoljeRJ3lU

https://datacommons.org/tools/map#%26sv%3DNumberOfMonths_WetBulbTemperature_35COrMore_RCP45_MinRelativeHumidity%26pc%3D0%26denom%3DCount_Person%26dt%3D2099%26pd%3Dcountry%2FUSA%26ept%3DCounty

<img width="939" alt="image" src="https://user-images.githubusercontent.com/6052978/157807470-5f5412fa-fca4-43fe-a587-2cbb1f155b10.png">

**Comment by beets** [comment]
Marking this as duplicate of #1167
