### ISSUE TITLE
[BUG] Clicking on any of populations from chart leads to a single population

### ISSUE THREAD

**Issue by tjann** [datacommonsorg/website#149]
### To Reproduce
URL: https://browser.datacommons.org/browser/geoId/1851876

### Expected behavior
Clicking Total will go to pop of Person
Clicking Female will go to pop of Person_Female
etc

### Screenshots

![image](https://user-images.githubusercontent.com/18621425/88129572-4368f280-cb8d-11ea-9fce-f3cd4bfb5c13.png)

**Comment by beets** [comment]
Fixed by #157 as well
