### ISSUE TITLE
[BUG] a few issues with visual tools on mobile

### ISSUE THREAD

**Issue by pradh** [datacommonsorg/website#1540]
(An umbrella bug to quickly add a few screenshots.)

## 1. Maybe "Plot places in" and "of type" can be separate lines so the search-box text shows up better?
<img src=https://user-images.githubusercontent.com/4375037/163083899-fbcb2b74-a4f9-4e6b-8efe-5e5fd52c8f0b.jpg width=250>

## 2. SV explorer table might need some different formatting for mobile:
<img src=https://user-images.githubusercontent.com/4375037/163084018-d8b53b95-8274-4c7b-8cae-23a328e698f0.jpg width=250>

## 3. For longish SVs in SV widget, the tool-tip may not be usable/readable.  Some way to scroll to see might be nice... (or if >30% or so wouldn't fit, then even skipping it might be better)
<img src=https://user-images.githubusercontent.com/4375037/163084062-4690619d-94e1-47fc-839e-d1869068441a.jpg width=250>

## 4. On the scatter, touching a dot opens up the place page in a new tab. I found that distracting/not-very-useful, rather it might be more useful to let the user see the pop-up about the place name and stat-values.
<img src=https://user-images.githubusercontent.com/4375037/163084222-cf5d9458-081b-41d8-b308-70f0fd16bf15.jpg width=250>

## 5. On map scatter, axis label appears truncated (without wrap around and ability to scroll).  Whereas the scatter plot view shows it well.
<img src=https://user-images.githubusercontent.com/4375037/163084524-7a69c03f-46b7-455d-94c1-c508b9fbc264.jpg width=250>
 
## 6. On clicking on a map tool link (like [this](https://staging.datacommons.org/tools/map#%26sv%3DDifferenceRelativeToBaseDate2006_Max_Temperature_RCP45%26pc%3D0%26denom%3DCount_Person%26pd%3Dcountry%2FUSA%26ept%3DCounty) on our main page), then doing "Select Variables", the highlighted nodes show up with a minus (-), and clicking that opens and closes the node turning into a plus (+), and only on a subsequent click does it actually open up.  (Loading existing timeline or scatter charts and doing the same has expected behavior)
<img src=https://user-images.githubusercontent.com/4375037/163085021-54bfeae3-0028-4d82-b394-a7df0273f73f.jpeg width=250>

**Comment by beets** [comment]
Thanks for filing - adding a few more:

No "left pane" when there are missing sv's

<img width="737" alt="image" src="https://user-images.githubusercontent.com/6052978/163089404-b217265b-4338-404a-8b3b-fa5ca22b279f.png">

The "screen" for the loading sign on scatter does not stretch to the full viewport height

**Comment by pradh** [comment]
Scatter has "Choose 2 statistical variables from the left pane." even on mobile, where there's no left pane.

![Screen Shot 2022-04-13 at 3 26 37 PM](https://user-images.githubusercontent.com/4375037/163281159-0593227b-1661-4eaf-8f5c-f219933cf9ed.png)

**Comment by beets** [comment]
A few more:

text box overflow
![Screenshot_20220421-134355](https://user-images.githubusercontent.com/6052978/166064178-06a9aa1e-9d58-400b-82eb-3dabc0ea4ae5.png | width=150)
![Screenshot_20220421-133608](https://user-images.githubusercontent.com/6052978/166064205-c15b598f-c08c-478d-9420-d5f1e12e876b.png | width=150)

map legend / size:

![Screenshot_20220421-135906](https://user-images.githubusercontent.com/6052978/166064316-8f37fea0-e1cd-43e2-8ac0-91dfd408de66.png | width=150)

documentation site overflow

![Screenshot_20220421-133527](https://user-images.githubusercontent.com/6052978/166064365-c7678506-d917-4bcc-9e88-221e7c646186.png | width=150)
