### ISSUE TITLE
[IITM-DC] Plot container CSS is off

### ISSUE THREAD

**Issue by SenthamizhanV** [datacommonsorg/website#1545]
### Describe the bug
Plot container CSS overlaps footer. Footer is fixed.

### To Reproduce
URL:  https://datacommons.iitm.ac.in/tools/timeline
Browser: Chrome

## Screenshots
![issue](https://user-images.githubusercontent.com/30504842/163242487-3783d694-26c3-48a5-b140-f7d59da88927.jpg)

**Comment by beets** [comment]
Please describe the issue more.  Screenshots are especially helpful.

This isn't an issue with our site. Can you make the footer shorter? That
will also give more room to the site content.

**Comment by SenthamizhanV** [comment]
Sure @beets, I will try that. Also added screenshot in initial post.
