### ISSUE TITLE
[BUG] Downloaded CSV fields should be quoted?

### ISSUE THREAD

**Issue by pradh** [datacommonsorg/website#1551]
Download any CSV, say from scatter [here](https://staging.datacommons.org/tools/scatter#%26svx%3DMedian_Income_Person%26dx%3DCount_Person%26svy%3DMedian_Age_Person%26dy%3DCount_Person%26epd%3Dcountry%2FUSA%26ept%3DCounty)

In something like this:

```
placeName,placeDCID,xDate,xValue-Median_Income_Person,yDate,yValue-Median_Age_Person,xPopulation-Count_Person,yPopulation-Count_Person
Autauga County, AL,geoId/01001,2019,29725,2019,38.2,null,null
Baldwin County, AL,geoId/01003,2019,29802,2019,43,null,null
```

the first field should probably be quoted:  "Autauga County, AL" since it includes the delimiter.

**Comment by dwnoble** [comment]
This has been resolved
