### ISSUE TITLE
[BUG] Browser charts are separating charts that differ by v

### ISSUE THREAD

**Issue by tjann** [datacommonsorg/website#161]
### Describe the bug

Populations that differ by one v used to be on 1 chart.

### To Reproduce
URL: https://staging.datacommons.org/browser/dc/p/he31kkfcbf5w2

### Screenshots

![image](https://user-images.githubusercontent.com/18621425/88341709-f30ba500-ccf2-11ea-921e-74f1b9713842.png)

**Comment by tjann** [comment]
It doesn't seem to always happen: e.g. this is the same stat var from the same dataset:

![Screen Shot 2020-07-23 at 3 04 58 PM](https://user-images.githubusercontent.com/18621425/88343383-226fe100-ccf6-11ea-8294-647db13f0a77.png)

**Comment by shifucun** [comment]
Closing this as the browser has switched to use the stat var hierarchy widget to show one chart per stat var.
