### ISSUE TITLE
[BUG] Hovering n/a data in Map Explorer shows datapoints from previous hover

### ISSUE THREAD

**Issue by enjoythecode** [datacommonsorg/website#1656]
### Describe the bug
When using the Map Explorer where some variables have no data, hovering over such places shows the data tooltip from the last place hovered.

### To Reproduce
URL: https://datacommons.org/tools/map#%26sv%3DGiniIndex_EconomicActivity%26pc%3D1%26denom%3DCount_Person%26pd%3DEarth%26ept%3DCountry%26domain%3D2.5133009106635767e-8%3A0.002044019790152496%3A0.004088014447295885
Browser: Google Chrome
Version 103.0.5060.64 (Official Build) (64-bit)

1. Go to ['...'](https://datacommons.org/tools/map#%26sv%3DGiniIndex_EconomicActivity%26pc%3D1%26denom%3DCount_Person%26pd%3DEarth%26ept%3DCountry%26domain%3D2.5133009106635767e-8%3A0.002044019790152496%3A0.004088014447295885)
2. Wait for the page to load
3. (carefully) without hovering over any other country, hover over Greenland, which should be a darker color than the rest of the map.
4. See that there is no tooltip (because there is no data)
5. Move mouse from Greenland to hover over Canada to the left
6. See that the tooltip is correctly displayed for Canada
7. Move mouse from Canada back to Greenland
8. See that a tooltip is displayed this time (inconsistent with #4), and that it is the same as the tooltip from #6

### Expected behavior
Do not show Canada's tooltip for Greenland.

### Screenshots
Step 3+4: No tooltip on Greenland:
![Screenshot 2022-07-08 12 59 57 PM](https://user-images.githubusercontent.com/22326517/178062264-4ab736cf-c79f-4fde-84ee-5efa384bd1cb.png)

Step 5+6: Canada's tooltip on Canada
![Screenshot 2022-07-08 1 00 03 PM](https://user-images.githubusercontent.com/22326517/178062318-d960995f-d069-4500-8a7f-158f2339c039.png)

Step 7+8: Moving back to Greenland shows Canada's tooltip
![Screenshot 2022-07-08 1 00 05 PM](https://user-images.githubusercontent.com/22326517/178062332-cf376be5-da5d-4019-a99f-30a313a56eac.png)

### Additional context
Refreshing the page resets the "last country" visited, which helps recreate steps 3 and 4.

**Comment by premr** [comment]
New interface does not seem reproduce able.
