### ISSUE TITLE
[BUG] Maybe give slightly more vertical space for charts

### ISSUE THREAD

**Issue by tjann** [datacommonsorg/website#167]
### Describe the bug

Just barely not enough s.t. we weed to click for the x axis.

### To Reproduce
URL: https://browser.datacommons.org/browser/dc/p/zyl5s3qrrmeq3

### Screenshots

![image](https://user-images.githubusercontent.com/18621425/88351869-a59c3180-cd0c-11ea-9a21-f010f21e7e58.png)

**Comment by shifucun** [comment]
Closing this with the new browser UI launched.
