### ISSUE TITLE
[BUG] Broken Examples Link

### ISSUE THREAD

**Issue by IanCostello** [datacommonsorg/website#170]
### Describe the bug
The examples page doesn't exist. 

### To Reproduce
URL: https://docs.datacommons.org/examples.html
Browser: Chrome (Browser Independent)

1. https://docs.datacommons.org/
2. Ctrl-f for "find how prevalent obesity is in US Cities or analyze genomic data "
3. Click on hyperlink.

### Expected behavior
The example page should exist or the link should be removed.

**Comment by beets** [comment]
Fix pending: https://github.com/datacommonsorg/docsite/pull/47
