### ISSUE TITLE
[BUG] Empty Fourth Page of Search Results 

### ISSUE THREAD

**Issue by clincoln8** [datacommonsorg/website#171]
### Describe the bug
When typing 'drug' into the search bar, the results show there are 4 pages. If the 4th page is clicked, it displays the No Results page. If the 3rd page is clicked, then it appropriately no longer displays a 4th page option.

### To Reproduce
URL: https://datacommons.org/search?q=drug
Browser: Chrome

1. Go to https://datacommons.org/search?q=drug
2. Click on '4' at the bottom of page to get the No Search Results page
3. Re enter 'drugs' into search bar
4. Click on '3' at bottom of page, notice that '4' is not longer an option

### Expected behavior
The first page after submitting a search should not display a 4th page if there are no results on the fourth page. The 3rd page is properly not showing the 4th page as an option

### Screenshots
first page after submitting search: https://screenshot.googleplex.com/u4jhxiqraos
no results page after clicking page '4': https://screenshot.googleplex.com/2ezpYD5HsVN
third page does not display a 4th page option: https://screenshot.googleplex.com/8TZrH6Geuyd

### Additional Context
The second page in the search results also displays a 4th page option.
Same thing happens when searching for 'drugs' vs 'drug'

**Comment by clincoln8** [comment]
Recently tried searching 'drug' and the 4th page had a result instead of displaying the No Results page. 
The problem still exists when searching 'drugs'.

**Comment by shifucun** [comment]
Not reproducible any more. The search is powered by custom search and this could be due to inconsistent paging from the indexing.
