### ISSUE TITLE
[BUG] Regression in StatVar Explorer links

### ISSUE THREAD

**Issue by pradh** [datacommonsorg/website#1739]
Suffixing `#<sv_dcid>` to https://datacommons.org/tools/statvar no longer works, and changed to `#sv=<sv_dcid>`.  Was that intentional?

Given that the tool has been in public use it might be nice to not break old links.  Though Google search doesn't indicate there are websites that link to it, but internal code search suggests there might be some broken links (e.g., http://cs/"https://datacommons.org/tools/statvar"), so maybe its fine and can mark this issue "Won't Fix" :)

**Comment by n-h-diaz** [comment]
yes this was intentional, as we added url params when incorporating dataset selection. 

I'm not sure if there's a way to add redirects for any existing links, but all of the links on website/g3 have been updated so will close for now
