### ISSUE TITLE
[BUG] Update the Datasets page

### ISSUE THREAD

**Issue by tjann** [datacommonsorg/website#180]
### Describe the bug
Datasets page is incomplete, but we claim it is a complete list.

### To Reproduce
URL: https://docs.datacommons.org/

### Screenshots

![image](https://user-images.githubusercontent.com/18621425/88710362-67678f00-d0cb-11ea-8669-1589e1295727.png)

**Comment by beets** [comment]
Can we reach out to everyone who imported the dataset to add a blurb? It can even be in a doc, so we can iterate on the text before checking it in.

**Comment by beets** [comment]
thanks for the fix!
