### ISSUE TITLE
[BUG] Change uptime check for removed api.

### ISSUE THREAD

**Issue by Fructokinase** [datacommonsorg/website#1808]
stat within place API is deleted but the alert is still up. This is causing the following uptime check to fail. Either delete this uptime check, or replace with a newer version (if there is one).

https://pantheon.corp.google.com/monitoring/uptime/api-stats-within-place?mods=-monitoring_api_staging&project=datcom-website-prod

**Comment by shifucun** [comment]
I have updated the uptime check and re-enabled the alert
