### ISSUE TITLE
[map] map tool unusable after error message

### ISSUE THREAD

**Issue by beets** [datacommonsorg/website#1893]
### Describe the bug
spinner does not go away after acknowledging the error message popup

### To Reproduce
URL: https://autopush.datacommons.org/tools/map#%26sv%3DCount_AstronomicalLowTideEvent%26pc%3D0%26denom%3DCount_Person%26pd%3DEarth%26ept%3DCountry
Browser: chrome

0. Start with URL above.
1. Next, choose country (USA) in place selector
2. In SV search, search for "area flood", select "Area of Flood Event"
3. In place type, select "0.5 arc degree"
4. Popup says "selected var is not available for chosen places". Click "OK"

### Expected behavior
I should be allowed to select other things

### Screenshots
![image](https://user-images.githubusercontent.com/6052978/207950365-c8a290f3-fe4f-4ff9-a4f7-083c5f6237d1.png)

**Comment by shifucun** [comment]
I will take a look
