### ISSUE TITLE
Histogram display issues

### ISSUE THREAD

**Issue by beets** [datacommonsorg/website#1942]
https://screenshot.googleplex.com/7dTvcsaeWdgGGoB - is data missing?
https://screenshot.googleplex.com/99ZNEuuy4BdtxM7 - empty dates aren't filled (we should see some gaps)

**Comment by beets** [comment]
https://screenshot.googleplex.com/BQeoZp6X7FCdpkY

**Comment by juliawu** [comment]
Fixed by PR #2086
