### ISSUE TITLE
[BUG] Investigate single datapoint for London population

### ISSUE THREAD

**Issue by beets** [datacommonsorg/website#200]
### Describe the bug
http://staging.datacommons.org/place?dcid=wikidataId%2FQ84

![image](https://user-images.githubusercontent.com/6052978/88865281-53e82100-d1bc-11ea-81ec-14f1e8f75c72.png)

**Comment by pradh** [comment]
There are stats from UNData and Wikidata sources. UNData is a single 2011 data point, while Wikidata is a time-series (http://staging.datacommons.org/browser/dc/p/qlyvv2jyqszzb).

I think the cache should build in both. I know the mixer does some ranking among sources [1]. For ones that aren't listed there, is the choice arbitrary? Should it be based on some heuristics on the data (has time-series or has the latest data, etc.)


[1] - https://github.com/datacommonsorg/mixer/blob/104d4db5b44f862beda42ee268d63a0678f7caae/server/stats.go#L33-L45

**Comment by beets** [comment]
@shifucun 

Should we add more to this list then? The preference for a time series is only for UI purposes, but if we weight it towards latest data, that will resolve to Wikidata which works better for both UI and analysis.

**Comment by pradh** [comment]
I will note that the date on Wikidata population stats will be all over the place across places. So won't be surprised if, for another place UNData was more recent.

**Comment by shifucun** [comment]
Looks like we need a bit complicated ranking on both data freshness and time span. I propose to:

1) First compare data time span. If one dataset has twice or more data than another, then pick it.
2) If two datasets have similar time span, pick the one that has latest data.

Any other ideas?
