### ISSUE TITLE
[BUG] Got Random Stats Vars (dc/xxx) when building the PV-tree

### ISSUE THREAD

**Issue by qlj-lijuan** [datacommonsorg/website#202]
### Describe the bug
When building the PV-tree, got statsvar: dc/cv35g4gzkth83 instead of Count_Person at the node position "Demographics -> Population"

### Screenshots
![image](https://user-images.githubusercontent.com/43854757/88867152-a0425980-d1da-11ea-8e4d-9d0f03e33224.png)
![image](https://user-images.githubusercontent.com/43854757/88867213-d1bb2500-d1da-11ea-94f5-b9ed085e662a.png)
![image](https://user-images.githubusercontent.com/43854757/88867275-06c77780-d1db-11ea-82a0-ec088bc6aa30.png)

**Comment by shifucun** [comment]
The stats var node is: https://datacommons.org/browser/dc/cv35g4gzkth83. @tjann can you take a look on if this is valid?

**Comment by tjann** [comment]
Maybe @Spaceenter ?

**Comment by qlj-lijuan** [comment]
two more nodes with the same problem: dc/g7m87nm4ec6j2, dc/7ej72pkcdjm49

**Comment by shifucun** [comment]
We decided to pick the human readable stats var in pv tree tool. The dc/xxx one will not be used.
