### ISSUE TITLE
[BUG] Two constraint StatPop not showing up in one constraint StatPop page

### ISSUE THREAD

**Issue by pradh** [datacommonsorg/website#207]
We have a 2 constraint StatPop with gdp + naics: https://staging.datacommons.org/browser/dc/p/x3xfzy0gk4y34 (https://screenshot.googleplex.com/gqrthTqLtMG)

I would have expected it show up under the "Sub-populations" section in: https://staging.datacommons.org/browser/dc/p/xm0tl88x5qr58 (https://screenshot.googleplex.com/2xBz2M9fBtW)

Any reason why it doesn't?

**Comment by shifucun** [comment]
The naics are filtered to top level ones: https://github.com/datacommonsorg/website/blob/master/static/js/browser/kg.js#L44-L58. This list now seems too restricted. We can expand this to a larger collections. Any suggestions on which ones to include? @pradh @tjann

**Comment by pradh** [comment]
Can we instead make it a regex-pattern + whitelist that allows: NAICS/10XX, NAICS/XX, NAICS/XX-YY patterns + a whitelist.

See datacommons/prophet/util/util.cc, lines 338-393.
