### ISSUE TITLE
[BUG] Blank timeline pages

### ISSUE THREAD

**Issue by beets** [datacommonsorg/website#211]
### Describe the bug
Timeline page is blank after clicking on the "university towns: income" link from the main page

### To Reproduce
URL: https://staging.datacommons.org/tools/timeline#&place=geoId/0606000,geoId/2511000,geoId/2603000,geoId/1777005,geoId/1225175,geoId/4815976&statsVar=Median_Income_Person
Browser: Chrome

### Screenshots

![image](https://user-images.githubusercontent.com/6052978/88968976-01af0a80-d265-11ea-98fa-9bcc9b9063ec.png)

**Comment by beets** [comment]
These links also broken:
https://staging.datacommons.org/tools/timeline#&&place=geoId/06085,geoId/06025&statsVar=Median_Income_Person
https://staging.datacommons.org/tools/timeline#&&place=geoId/1304000,geoId/4982950&statsVar=Median_Income_Person
https://staging.datacommons.org/tools/timeline#&&place=geoId/0655282,geoId/0620956&pc=0&statsVar=Median_Income_Person

**Comment by shifucun** [comment]
Maybe a browser cache issue. Can you try hard refresh and see if they work?

**Comment by beets** [comment]
Yep, I still see it with my cache disabled.
