### ISSUE TITLE
Use dedicated cache data for place page

### ISSUE THREAD

**Issue by shifucun** [datacommonsorg/website#214]
The cache is available here: curl -X POST 'datacommons.endpoints.datcom-mixer-staging.cloud.goog/node/landing-page'  -d '{ "dcids": ["geoId/12"]}'

API details: https://github.com/datacommonsorg/mixer/blob/master/proto/mixer.proto#L413-L418

For the primary page, can call this API without stats var. For charts of similar/related place, can add the selected stats vars in the request to limit the data size.

**Comment by beets** [comment]
Still pending for comparison charts, will open a separate PR if it turns out to be an issue
