### ISSUE TITLE
[BUG] Add y-axis label in timeline charts

### ISSUE THREAD

**Issue by beets** [datacommonsorg/website#219]
### Describe the bug
It will be nice to have axis labels when appropriate, e.g. when there are units involved. This is probably more important when there are multiple groups of charts.

http://staging.datacommons.org/tools/timeline#&place=geoId/01&statsVar=Count_Person,0,0__Median_Age_Person,0,1__Median_Income_Person,0,2

**Comment by shifucun** [comment]
This can share the save logic as in http://browser.datacommons.org/tools/timeline#&ptpv=Person,count,maritalStatus,Divorced,age,Years15Onwards&place=geoId/0668000

**Comment by qlj-lijuan** [comment]
The link is not valid now. Do you have a new link? Should we use measurement property as y-label?

**Comment by qlj-lijuan** [comment]
> This can share the save logic as in http://browser.datacommons.org/tools/timeline#&ptpv=Person,count,maritalStatus,Divorced,age,Years15Onwards&place=geoId/0668000

**Comment by shifucun** [comment]
Sorry this is the link: https://github.com/datacommonsorg/website/blob/master/static/js/browser/plot.js#L238-L285. Can make this a util function
