### ISSUE TITLE
[BUG] Don't redraw entire statvar panel on selection change

### ISSUE THREAD

**Issue by beets** [datacommonsorg/website#220]
### Describe the bug
The state of the statvar panel is completely refreshed whenever an option is unselected. It's very jarring when there are multiple menus open.

### To Reproduce
URL: http://localhost:8080/tools/timeline#&place=geoId/0606000,geoId/2511000,geoId/2603000,geoId/1777005,geoId/1225175,geoId/4815976&statsVar=Count_Person_EducationalAttainmentKindergarten,2,0,2

1. Expand many options in the stat var menu
2. Choose an option
3. Unselect any option

### Expected behavior
Options that have been expanded, should stay expanded.

### Screenshots
https://screencast.googleplex.com/cast/NTYwOTcwNzY0NzUzMzA1NnwzYzhlOGJlZS02Ng

**Comment by shifucun** [comment]
Right now each checkbox expansion state is based on the selected stats vars. We can keep an array of "ever selected" stats var in StatsVarMenu component, and use that for expansion status
