### ISSUE TITLE
[BUG] Add 15px margin between chart and legend

### ISSUE THREAD

**Issue by beets** [datacommonsorg/website#221]
The legend and the chart needs some spacing. Let's try 15px

![image](https://user-images.githubusercontent.com/6052978/88987672-87de4780-d28b-11ea-8eac-c42bc868dbb1.png)

**Comment by qlj-lijuan** [comment]
To confirm, which legend are you referring to? The legend on the right side?

**Comment by beets** [comment]
yes, the legend on the right side.
