### ISSUE TITLE
[BUG] Stats Var menu is missing when there is only Count_Person 

### ISSUE THREAD

**Issue by shifucun** [datacommonsorg/website#230]
### Describe the bug
Stats Var menu is missing one there is only one stats var for a place

### To Reproduce
URL: https://staging.datacommons.org/tools/timeline#&statsVar=Count_Person&pc=0&place=wikidataId/Q160173

### Expected behavior
The menu should show up with "Population" checkbox checked.

**Comment by qlj-lijuan** [comment]
For the link above, the place chip name is empty, is that expected?

**Comment by shifucun** [comment]
> For the link above, the place chip name is empty, is that expected?

Yep, the name is missing in the graph.
