### ISSUE TITLE
[BUG] Timelines missing age ranges that show up in browser

### ISSUE THREAD

**Issue by pradh** [datacommonsorg/website#231]
In Timelines tool, pick UK.

On LHS under Age there are only two ranges: https://screenshot.googleplex.com/oX9cHbCQ6hy

There are several more ranges seen in the browser: https://screenshot.googleplex.com/yEtGwoZAgFX

**Comment by qlj-lijuan** [comment]
The age ranges in the UI nodes are deliberately filtered. Do want to change this? @shifucun

**Comment by shifucun** [comment]
> The age ranges in the UI nodes are deliberately filtered. Do want to change this? @shifucun

Need to discuss with the team and see what behavior should it be. 

- One option is to include all the 5 year age range, that might work for both euro stats data and us census data
- Another option is to dynamically determine continuous age range from available stats var and show those on the menu.

**Comment by shifucun** [comment]
Fixed with the new stat var widget
