### ISSUE TITLE
[BUG] Set default stats var to be Count_Person when place is selected

### ISSUE THREAD

**Issue by shifucun** [datacommonsorg/website#232]
To Reproduce
URL: https://staging.datacommons.org/tools/timeline#&place=geoId/0647766

### Expected behavior
Should show the Population chart.

**Comment by shifucun** [comment]
Need to add React test to cover the regression.

**Comment by shifucun** [comment]
In this case, we should do the special handling:

1) Show Count_Person chart on the the chart region
2) Do not check the stats var menu
3) Do not change the url

**Comment by shifucun** [comment]
@beets Shall we show a hint of "Please pick statistical variables from the left hand side menu" in this case?

**Comment by beets** [comment]
A hint sounds good - we do that for stat var explorer!

![image](https://user-images.githubusercontent.com/6052978/133862835-373791d9-ab8c-4c25-a23a-c2f265f27c8e.png)

**Comment by beets** [comment]
related: #232
