### ISSUE TITLE
[NL] Topic - minority population, economical housing

### ISSUE THREAD

**Issue by pradh** [datacommonsorg/website#2365]
Cases where there is are SVs in search index, but for a broad query, result should be better curated.

[which county has the highest minority population] -- minority population
[what's the best place to get a cheap house in the usa] -- economical housing

**Comment by lucy-kind** [comment]
Because "economical" is a subjective topic and depends on cost of living amongst other factors for each area, this topic shall now be Housing Costs.

**Comment by lucy-kind** [comment]
added to embeddings

![image](https://user-images.githubusercontent.com/63422135/228686046-a28aaaac-8494-445e-ae9a-eb9ff4eca33f.png)

**Comment by pradh** [comment]
@lucy-kind could we use these issues to track end-to-end that a topic query shows up satisfactorily on the NL interface?  (including SV detection, fulfillment, UI issues, etc)

The minority one shows up reasonably, but the names seem odd:
![image](https://user-images.githubusercontent.com/4375037/228700094-0ce40cd3-5736-4b8a-bf5e-2a7e0d689718.png)

The economical housing doesn't show up yet (pending an autopush build perhaps):
![image](https://user-images.githubusercontent.com/4375037/228700167-35e38e90-41c9-497e-aba1-b813ef85f411.png)
