### ISSUE TITLE
NL: Topic - Wet bulb temperatures

### ISSUE THREAD

**Issue by lucy-kind** [datacommonsorg/website#2379]
Create topic for wet bulb temperature events

include the following SVS here: https://docs.google.com/spreadsheets/d/1C0p5Ex9ZCLnhC2W9oSqPb6nfOitO9uI7ptCcqFkyT6o/

**Comment by pradh** [comment]
Lucy: please create a topic entry for this in our KG, and then we can add just that one line for that topic to the sheet.

Also, note that we originally had wetbulb in the main index, and removed it because it showed up for "temperature" results.

**Comment by pradh** [comment]
We probably want to validate this end-to-end?
