### ISSUE TITLE
[NL] Make unit names in charts shorter

### ISSUE THREAD

**Issue by pradh** [datacommonsorg/website#2386]
Things like InflationAdjustedUSD_CurrentYear/USDollar ("family earnings in california"), Hundredweight ("agricultural output in california"), etc

**Comment by pradh** [comment]
`shortDisplayName` in KG SG.  And FE will make an API call to use it?

**Comment by pradh** [comment]
Units in DC: https://docs.google.com/spreadsheets/d/1dVm8SK3a3xvXpNzENNgh6KIx8xvf9epSaKEMqdHGcDU/edit#gid=2015142530

**Comment by lucy-kind** [comment]
Update: Out for internal review

**Comment by lucy-kind** [comment]
Internal change submitted. Assigning to shanth for front end

**Comment by pradh** [comment]
@chejennifer could you help make the change to use `shortDisplayName` in FE for unit names?  Then we can hopefully get rid of the static maps we have.
