### ISSUE TITLE
NL: Map/ranking/bar/scatter charts should show dates

### ISSUE THREAD

**Issue by pradh** [datacommonsorg/website#2392]
example:

![image](https://user-images.githubusercontent.com/4375037/223791261-a0e76cd5-928f-492a-b0f3-690c202ce663.png)

**Comment by pradh** [comment]
@beets @chejennifer

**Comment by chejennifer** [comment]
If you add '${date}' in the chart title, when the tile is rendered, that string will be replaced with the actual date of the data

**Comment by pradh** [comment]
Thanks @chejennifer. So what chart types specifically support it?  It seems ranking table might not?

![image](https://user-images.githubusercontent.com/4375037/223874397-3e82a77f-5d09-4b13-9478-20a0badfdfdb.png)

**Comment by pradh** [comment]
Bar chart doesn't show too?

![image](https://user-images.githubusercontent.com/4375037/223877684-23b6ac4d-8e42-4dbc-b790-f14d3b7d1ebe.png)

**Comment by beets** [comment]
Any chart that shows a single obs should support it (looks like we left out
quite a few in implementation). Bounce the bug back to us and we can fill
it in.
