### ISSUE TITLE
Per capita not working on timeline tool

### ISSUE THREAD

**Issue by rvguha** [datacommonsorg/website#242]
Per capita not working on timeline tool

**Comment by shifucun** [comment]
Maybe due to browser cache, I tried production and seems working:
![image](https://user-images.githubusercontent.com/5951856/89243628-431f1d00-d5b9-11ea-8648-ac6e8686d956.png)

**Comment by shifucun** [comment]
For per capita, when y value is less than 0, need to change the text display from "500m" to 0.5
