### ISSUE TITLE
NL: Show earth/world map on place overview

### ISSUE THREAD

**Issue by jehangiramjad** [datacommonsorg/website#2451]
When earth/world is the place detected/defaulted, show the map of the world. 

Sample query to try: "top earthquakes earth" -> notice, "earth" is detected but no map shown.

**Comment by pradh** [comment]
That query now shows the world map:

![image](https://user-images.githubusercontent.com/4375037/229259991-77a82ab4-1be8-4a39-8ca8-d74862fd221a.png)

But just the query [earth] not showing a map is still a problem.  The same problem exists for continents too.

Closing this one as a dup of https://github.com/datacommonsorg/website/issues/2529.
