### ISSUE TITLE
NL: Expand containedIn logic to handle more ambiguous place types like "places in" and "regions in"

### ISSUE THREAD

**Issue by juliawu** [datacommonsorg/website#2467]
We should support queries that ask for contained in places, but don't specify an exact admin area level. For example "US regions with the most unbalanced gender ratio" should show a ranking of states/counties/cities in the US by gender ratio, picking state/county/city depending on which admin area level we have data for.

Example queries:
* least religious place in USA
* US regions with the most unbalanced gender ratio

**Comment by pradh** [comment]
Fixed in #2538 

eg [US regions with the most unbalanced gender ratio] shows states in US for some (somewhat unrelated) SVs.
