### ISSUE TITLE
NL: Alternate ways of referring to the context

### ISSUE THREAD

**Issue by jehangiramjad** [datacommonsorg/website#2477]
Query sequence used: https://autopush.datacommons.org/nl#q=are%20there%20any%20cyclones%20in%20asia;i%20want%20to%20know%20about%20the%20education%20rate%20in%20america;how%20about%20these%20rates%20in%20europe(https://autopush.datacommons.org/nl/#q=are%20there%20any%20cyclones%20in%20asia;i%20want%20to%20know%20about%20the%20education%20rate%20in%20america;how%20about%20these%20rates%20in%20europe&a=true)&a=true

Note that the third query says: "how about these rates in europe". The user is referring to their previous query (context) but the current query does not use the past context. 

This is a difficult case because there are many ways to refer to the previous context.

**Comment by pradh** [comment]
Do you think we dedupe this with https://github.com/datacommonsorg/website/issues/2452 ?  (To reduce the number of disparate bugs and collect similar-ish bugs together)

**Comment by jehangiramjad** [comment]
> Do you think we dedupe this with #2452 ? (To reduce the number of disparate bugs and collect similar-ish bugs together)

Added the details to #2452 and will close this issue now.
