### ISSUE TITLE
[BUG] Consider unifying the different School Enrollment categories

### ISSUE THREAD

**Issue by pradh** [datacommonsorg/website#248]
On Timeline tool LHS, we have three variable categories that all logically represent school enrollment, but are called different things: https://screenshot.googleplex.com/P6N458EvScb

We should consider unifying them.

One possible option:
  + Educational Attainment
  + School Enrollment
     + By type of school
     + By level of school
     + By detailed level of school

**Comment by beets** [comment]
i believe this has been fixed
