### ISSUE TITLE
Remove default statsVar Count_Person when other statsVars are selected 

### ISSUE THREAD

**Issue by qlj-lijuan** [datacommonsorg/website#251]
### Describe the bug
When no places are selected, default statsVar Count_Person is added. 
In the old timeline tool, the default statsVar would disappear if users select other statsVars, now it stays. 

### To Reproduce
URL: https://staging.datacommons.org/tools/timeline#
Browser: Chrome 

1. Go to https://staging.datacommons.org/tools/timeline#
2. Search for a place, e.g. United states
3. select a new statsVar

### Expected behavior
Expect "Count_Person" to disappear after step3

**Comment by beets** [comment]
I suppose we've fixed this by removing the default behavior of showing population. I think having the default chart helps usability... was it removed on purpose? If not, should we bring it back?

@qlj-lijuan feel free to ignore this if you've already logged off for the day :)

**Comment by qlj-lijuan** [comment]
It was not removed on purpose. I didn't have time to add the default chart after the refactoring. We should add it back.

**Comment by beets** [comment]
we should add a message telling users to pick a stat var
