### ISSUE TITLE
NL: ContainedIn places at the same level as the containing place should not trigger a contained in chart

### ISSUE THREAD

**Issue by jehangiramjad** [datacommonsorg/website#2527]
Example query: how does the GDP in the US compare to other countries

Expected behavior(s): it should either just keep showing the US GDP or go one level higher for the containing place (world/earth?) to show comparison across countries. Given the current implementation limitations, just ignoring the contained in classification is probably best when the containing place + contained in type are both the same (Country).

**Comment by pradh** [comment]
Fixed in #2538
