### ISSUE TITLE
[BUG] Show error message when we fail to download data

### ISSUE THREAD

**Issue by beets** [datacommonsorg/website#260]
### Describe the bug
Right after the mixer was deployed this morning, the timeline tool was unresponsive while the mixer was restarting. We should show error messages to the user, instead of staying unresponsive (turns out there were a lot of errors showing on the console).

### To Reproduce
URL: http://datacommons.org/tools/timeline#&&place=geoId/1304000,geoId/4982950&pc=1&statsVar=Count_Person_Female__Count_Person_Male

An equivalent way to reproduce this is to return 500 from all our url endpoints in the frontend.

### Expected behavior
Error message to the user. Instead, it seemed as if the links were broken and the app unresponsive (even selecting places from search failed).

### Screenshots
Copy/pasting screenshots from the clipboard into this form works!

### Additional context
![image](https://user-images.githubusercontent.com/6052978/89671768-6d622a80-d898-11ea-8984-62830c4e7585.png)

**Comment by shifucun** [comment]
This has been fixed with uptime check in GKE pod. A pod is in ready state only when all the containers (mixer, esp, website) are in ready state.
