### ISSUE TITLE
NL: bar chart with lots of variables is hard to read

### ISSUE THREAD

**Issue by chejennifer** [datacommonsorg/website#2932]
in this example: https://screenshot.googleplex.com/9yrFJwF2nwWSEKs

1. When the chart says "A compared with other variables", A doesn't appear in the legend, so it is hard to see how it compares to others.

2. The colours shades for bars are too close to find the matching legend. Maybe add a hover tooltip?

**Comment by pradh** [comment]
The attached PR addresses (1).  Defer to you and @dwnoble for (2).
