### ISSUE TITLE
[BUG] Y axis value is duplicated

### ISSUE THREAD

**Issue by wh1210** [datacommonsorg/website#298]
### Describe the bug
For some charts, the y axis value is duplicated.

### To Reproduce
URL: https://datacommons.org/browser/geoId/06
Browser: Chrome

1. Go to 'https://datacommons.org/browser/geoId/06'
2. Scroll down to 'count (CensusACS5yrSurvey) of Person' chart.

### Expected behavior
The y axis value should be incremental instead of duplicated.

### Screenshots
https://screenshot.googleplex.com/TupvTgdBZCY

**Comment by beets** [comment]
it's been fixed
