### ISSUE TITLE
Layout of the Economics category in the statsVar Menu

### ISSUE THREAD

**Issue by qlj-lijuan** [datacommonsorg/website#319]
Here's current look for the economics statsVars, the new ones are in the red box. 

I'm looking for some feedback on the layout, such as 
- do we need to do some sorting
- should we move things like "labor force" to the category "Employment"
- do we need a better name for "Activity Source"

![image](https://user-images.githubusercontent.com/43854757/90672567-4dc9eb00-e224-11ea-8fd2-c6a6c9bd0eee.png)

**Comment by beets** [comment]
Related: #385
