### ISSUE TITLE
[Feedback] Typo in Timeline tool for "Sleep less than 7 hours"

### ISSUE THREAD

**Issue by edumorlom** [datacommonsorg/website#320]
### Feedback
There is a typo in "Health Behaviors".
It should be "Sleep Less Than 7 Hours" instead of "Sleep Less Than7 Hours".

### About
URL: http://datacommons.org/tools/timeline
Browser: Google Chrome

### Screenshots
![image](https://user-images.githubusercontent.com/11444894/90677291-2591ba80-e22b-11ea-8e9a-8b95e2b38fab.png)

**Comment by beets** [comment]
it's been fixed
