### ISSUE TITLE
[Feedback] consider bar width reflecting interval width

### ISSUE THREAD

**Issue by tjann** [datacommonsorg/website#326]
### Feedback
For example, it at first looks surprising that there are so many people in the oldest age bracket, but it's probably just because it is a larger range. I know this is kind of tricky, since there is often no upper bound (age, income, etc. can theoretically go on...)

![image](https://user-images.githubusercontent.com/18621425/90911695-2c850e00-e38e-11ea-8d45-b8c4f244cf23.png)

**Comment by beets** [comment]
for reference:
![image](https://user-images.githubusercontent.com/6052978/140803348-0c5ed54a-83a2-4d3d-85ed-f5c2685a939b.png)
