### ISSUE TITLE
[BUG] Place page age across places charts seem off

### ISSUE THREAD

**Issue by tjann** [datacommonsorg/website#327]
### Describe the bug
Age across places seems off in several ways.

### Expected behavior
I expected the MTV chart to always show, since this is the MTV place page. I think if places don't have data, then the chart wouldn't show either.

![image](https://user-images.githubusercontent.com/18621425/90912503-90f49d00-e38f-11ea-9b70-6b125d856ef0.png)

I also expected if data exists for one of the age across places chart, it would exist for the other

<img width="1190" alt="Screen Shot 2020-08-21 at 9 17 40 AM" src="https://user-images.githubusercontent.com/18621425/90912276-2d6a6f80-e38f-11ea-96d0-9f0555f0f7e2.png">

**Comment by shifucun** [comment]
These issues have been solved after using merged landing page cache on server side https://github.com/datacommonsorg/website/pull/476
