### ISSUE TITLE
[BUG] Place page (MTV)-- missing sleep less than 7 hours

### ISSUE THREAD

**Issue by tjann** [datacommonsorg/website#329]
### Describe the bug

The chart is empty in the place page chart:

![image](https://user-images.githubusercontent.com/18621425/90914483-db2b4d80-e392-11ea-8142-92cbcb42cdb3.png)

but you can see it in timeline tool:
<img width="1005" alt="Screen Shot 2020-08-21 at 9 44 20 AM" src="https://user-images.githubusercontent.com/18621425/90914508-e5e5e280-e392-11ea-95fe-7f558524c225.png">

**Comment by beets** [comment]
This is WAI - the data for that is only available for 2016, where as others have 2017 data.

We could show 2016 data instead though, wdyt?
This also brings to mind a feature request - we should show the year / date we are aggregating data for.

**Comment by tjann** [comment]
I think it makes sense to show 2016 data. BTW what API are you using for this?  Some of our APIs should have the option for showing any latest stat.

**Comment by beets** [comment]
We're using the old stat REST API, and this has the same issue as in
Python, where you'd want to be able to compare data from the same date.
Which is why we should lift that logic up to the mixer, and make the
"latest" designation stricter if it's for multiple stat vars

**Comment by beets** [comment]
fixed - we show the latest data that is available for all variables shown
