### ISSUE TITLE
[BUG] Santa Clara County Environment section is empty

### ISSUE THREAD

**Issue by tjann** [datacommonsorg/website#330]
### Describe the bug

The Santa Clara County place page environment section is empty. When you click MORE CHARTS> , the [environment page](http://datacommons.org/place?dcid=geoId/06085&topic=Environment) does have a chart. Not sure if this is intended.

<img width="1328" alt="Screen Shot 2020-08-21 at 9 46 40 AM" src="https://user-images.githubusercontent.com/18621425/90914744-39f0c700-e393-11ea-87d1-866da1c3866d.png">

### To Reproduce
URL: http://datacommons.org/place?dcid=geoId/06085

**Comment by beets** [comment]
Added equivalent charts to both the topic and overview sections so this doesn't happen again
