### ISSUE TITLE
[BUG] Measurement Qualifier not shown in UI when charts only differ by it

### ISSUE THREAD

**Issue by tjann** [datacommonsorg/website#333]
### Describe the bug
If two charts are the same except for mQual, we should display mQual.

### To Reproduce
https://staging.datacommons.org/browser/dc/p/jdhqcwqjrb0y1

First and last chart:
<img width="680" alt="Screen Shot 2020-08-21 at 10 32 34 AM" src="https://user-images.githubusercontent.com/18621425/90918510-a1aa1080-e399-11ea-814a-e29207c2a9d8.png">

**Comment by shifucun** [comment]
All properties are shown on the latest graph browser chart.
