### ISSUE TITLE
[Feedback] Set a default obs_props in the specs of the PV-tree

### ISSUE THREAD

**Issue by qlj-lijuan** [datacommonsorg/website#345]
### Feedback
Currently we add a new level when there're multiple obs_props in the same spec, and keep on the same level when there's only one obs_props. We may consider set one of the obs_props as the default one, which does not create a new level even if there're multiple obs_props.
An example is:
![image](https://user-images.githubusercontent.com/43854757/91247909-6739ce00-e721-11ea-93a4-f964c8c70140.png)
We should not create a new level for "Count"

spec: {
  pop_type: "Person"
  obs_props: {
    mprop: "count"
    stat_type: "measuredValue"
    name: "Count"
  }
  obs_props: {
    mprop: "lifeExpectancy",
   stat_type: "measuredValue",
   name: "Life Expectancy"
  } 
  vertical: "Demographics"
  cprop: "gender"
}

**Comment by shifucun** [comment]
Can make the count checkbox at "Female" level?

**Comment by qlj-lijuan** [comment]
Yes. I think Count checkbox should be at "Female" level. We can specify it in the spec so that we do not put it in the new level when building the tree.
