### ISSUE TITLE
[Feedback] Quicker access to browser nodes

### ISSUE THREAD

**Issue by pradh** [datacommonsorg/website#360]
How does one navigate to the browser page for a place?
1. Use default search
2. Use BQ (search_dc) search
3. Use auto-completion search on place page, and edit the URL to point to browser page.

(1) is pretty unusable. (2) is slow, and not typo resilient. (3) is what I use.

It would help reduce key-strokes/mouse-clicks involved if there was a link to the browser page somewhere on the place page.

Even better is place auto-completion search for the browser, but that's probably more work.

**Comment by beets** [comment]
i don't know how much we want to support/encourage visits to the browser pages. perhaps for development purposes, we can have a chrome bookmark / extension to navigate between the two.
