### ISSUE TITLE
[BUG] Place explorer chart incorrectly reports "US Census" as source

### ISSUE THREAD

**Issue by pradh** [datacommonsorg/website#361]
The population of Wellington NZ is not from US Census.

http://staging.datacommons.org/place?dcid=wikidataId%2FQ23661
(https://screenshot.googleplex.com/5GGDdkWXpASgnkA)

**Comment by beets** [comment]
We're now showing google.com which is not what we want either.

**Comment by tjann** [comment]
Related: we show China's labor force participation is from BLS: https://screenshot.googleplex.com/A7BXkUjQNy6r4ug and GDP from Eurostat. LMK if I should file a new bug.

**Comment by beets** [comment]
please test against staging. we now use the source returned from the api but it hasn't been pushed.
what we should also fix is "github.com" as a source
http://staging.datacommons.org/place?dcid=country%2FCHN

**Comment by tjann** [comment]
I see, thanks @beets .

Agreed. I sent a fix in g3.
