### ISSUE TITLE
[BUG] Investigate huge per capita numbers for age in mountain view, ar

### ISSUE THREAD

**Issue by beets** [datacommonsorg/website#379]
http://staging.datacommons.org/place?dcid=geoId%2F0547540&topic=Demographics

![image](https://user-images.githubusercontent.com/6052978/91773436-9cb83e80-eb9b-11ea-807c-61eb043bed7b.png)

**Comment by beets** [comment]
Check Muncie, IN:
http://staging.datacommons.org/place?dcid=geoId%2F1851876&topic=Demographics

![image](https://user-images.githubusercontent.com/6052978/91773616-fae52180-eb9b-11ea-990a-d39e65d3e20c.png)

**Comment by shifucun** [comment]
The population data of Muncle has some issue:

![image](https://user-images.githubusercontent.com/5951856/95116194-82720300-06fb-11eb-86b3-9b6f43fa3ca2.png)

**Comment by tjann** [comment]
this is in prod now: https://screenshot.googleplex.com/6KBngDebxtgLVUG

![image](https://user-images.githubusercontent.com/18621425/95400459-8189ce80-08bf-11eb-82e8-f07aad1490aa.png)
 Moving discussion offline.
