### ISSUE TITLE
Per capita denominator

### ISSUE THREAD

**Issue by rvguha** [datacommonsorg/website#386]
Per capita denominator is sometimes wrong. 
1. Should factor in dependent pv
2. Don't know how to do this, and we might need new UI, but need to find a way to handle things like "poverty rate amongst women". To get the rate we shouldn't divide by population, but by the number of women.

**Comment by shifucun** [comment]
Now the "per capita" is only based on "Count_Person". As discussed, we will have a "calculator" tool where users can enter a range of math operators on stat vars.
