### ISSUE TITLE
[BUG] Issues with running test script locally

### ISSUE THREAD

**Issue by KilimAnnejaro** [datacommonsorg/website#3923]
### Describe the bug
In following the directions in https://github.com/datacommonsorg/website/blob/master/README.md, there look to be a couple of dep issues in the script. For sure pytest and flask are not currently being installed correctly, but also there is this bug:

```
___________ ERROR collecting server/tests/services/discovery_test.py ___________
ImportError while importing test module '/Users/jengishchokusu/website-1/server/tests/services/discovery_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
server/__init__.py:23: in <module>
    from flask_babel import Babel
E   ModuleNotFoundError: No module named 'flask_babel'
```

### To Reproduce
Running on Mac in terminal.

1. Follow the directions in readme to run tests.

### Expected behavior
Should run tests and not fail on dependencies.

**Comment by wittrock** [comment]
I can't reproduce this with a checkout from this morning. My process was:
1. clone the repo
2. run `./run_tests.sh --setup_python`
3. run `./run_tests.sh -a`

Can you confirm you ran the setup_python step first? I'll send a PR to update the docs to require that, as it does seem unclear.
