### ISSUE TITLE
[BUG] Autocomplete for places: select first suggestion on "Enter"

### ISSUE THREAD

**Issue by tjann** [datacommonsorg/website#411]
### Describe the bug
I believe it's common for the `<Enter>` key to trigger selection of the first suggestion of a dropdown/autocomplete. Please ignore the bug if I'm wrong.

### To Reproduce
URL: https://datacommons.org/tools/timeline#place=geoId%2F4819000

**Comment by beets** [comment]
yea, this isn't a common pattern unless we also auto-complete in the search box.

**Comment by tjann** [comment]
Reopening based on discussion in #700

**Comment by beets** [comment]
It's been fixed

**Comment by tjann** [comment]
Sorry, maybe it is confusing because the title has the word "places" but this bug is for the timeline feature. As far as I can tell, the timeline feature does not have the autocomplete selection: https://screencast.googleplex.com/cast/NjI2MzY0NDkwMTg2NzUyMHxlMmMwODhjOC1hOA
