### ISSUE TITLE
[BUG] Double quote characters in directory names cause clone error

### ISSUE THREAD

**Issue by mapsiva** [datacommonsorg/website#4145]
### Describe the bug
Error cloning repository at the same directory. Maybe the directory name containing quotes triggers this error. Please, rename this file and remove quotes from directory name.

Cloning into 'website'...
remote: Enumerating objects: 53683, done.
remote: Counting objects: 100% (1006/1006), done.
remote: Compressing objects: 100% (593/593), done.
remote: Total 53683 (delta 505), reused 733 (delta 341), pack-reused 52677
Receiving objects: 100% (53683/53683), 84.08 MiB | 12.54 MiB/s, done.
Resolving deltas: 100% (38884/38884), done.
fatal: cannot create directory at 'server/integration_tests/test_data/detection_api_multivar/compare"malepopulation"with"femalepopulation"': Invalid argument
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

### To Reproduce
Git client: 2.33.1
OS: DeepIn 23 (debian based distro)

1. git clone https://github.com/datacommonsorg/website.git

### Expected behavior
Successful checkout

**Comment by mapsiva** [comment]
![error](https://github.com/datacommonsorg/website/assets/334335/70f62bae-b636-4bfe-93ff-1cd1ce9e3533)

**Comment by shifucun** [comment]
This is fixed now. Can you try again?
