### ISSUE TITLE
Use choropleth chart to replace "nearby places" chart 

### ISSUE THREAD

**Issue by shifucun** [datacommonsorg/website#422]
Remaining TODOs

- [x]  Getting the exploreURL for the charts
- [x]  Getting the sources for the charts
- [x]  Clean up scaling and units (eg. right now, I append unit to the end of the value, but when the unit is $, it should be appended to the front)
- [x]  Try using the date alignment for getting data for choropleth
- [x]  Deal with when the tooltip message is too long
- [x]  make the colors of my choropleths match the colors of the category
- [x]  add choropleth charts for county pages (show state choropleth)
- [x]  decouple choropleth promises from main data fetch
- [x]  add click target on each subregion
- [x]  geojson type
- [x]  look into package for drawing choropleth for puerto rico
- [x]  replace "places within" charts for state / country on overview page with choropleth if possible

**Comment by chejennifer** [comment]
Remaining TODOs

- [x]  Getting the exploreURL for the charts
- [x]  Getting the sources for the charts
- [ ]  Clean up scaling and units (eg. right now, I append unit to the end of the value, but when the unit is $, it should be appended to the front)
- [x]  Try using the date alignment for getting data for choropleth
- [ ]  Deal with when the tooltip message is too long
- [ ]  Using viridis or something else for the color scale
- [ ]  make the colors of my choropleths match the colors of the category
- [ ]  geojson type
- [ ]  add click target on each subregion

**Comment by beets** [comment]
#532
