### ISSUE TITLE
Have better/precise domain url for cache data

### ISSUE THREAD

**Issue by shifucun** [datacommonsorg/website#429]
The current provenance domain is very general. For example, the EuroStats data have a provenance of europa.eu instead of ec.europa.eu/eurostat/data/database. It's better to have more precise provenance url.

**Comment by shifucun** [comment]
@tjann Is this something we can do in the manifest?

**Comment by tjann** [comment]
We have both provenance url and provenance domain. Rather than talk about cache, should we talk about whether the cache should also include the url?

**Comment by shifucun** [comment]
Include the url is definitely better!

**Comment by beets** [comment]
Both url and display name would be best

**Comment by beets** [comment]
can we start with a static mapping from domain to full url / display name?
