### ISSUE TITLE
[place] Unable to open place page for American Samoa

### ISSUE THREAD

**Issue by chejennifer** [datacommonsorg/website#530]
Unable to load place page for "American Samoa" when trying on staging (http://staging.datacommons.org/place/country/ASM). Seems to be getting an error when retrieving data. 

![image](https://user-images.githubusercontent.com/69875368/95610349-0c301200-0a15-11eb-8e40-30326292c4e2.png)

**Comment by shifucun** [comment]
https://github.com/datacommonsorg/mixer/pull/331 will fix this
