### ISSUE TITLE
[place] Can't navigate to Washington State through searching

### ISSUE THREAD

**Issue by chejennifer** [datacommonsorg/website#531]
Can't navigate to the place page for Washington State when trying to search for it. Tried searching for "washington", "washington, USA", "washington state" and none of those gave me the option to go to the Washington State page. 

![Screenshot 2020-10-09 at 9 44 09 AM](https://user-images.githubusercontent.com/69875368/95610680-8a8cb400-0a15-11eb-807a-540f3876a89c.png)
![Screenshot 2020-10-09 at 9 43 42 AM](https://user-images.githubusercontent.com/69875368/95610705-92e4ef00-0a15-11eb-8bf0-26cfbfd3b42c.png)
![Screenshot 2020-10-09 at 9 41 00 AM](https://user-images.githubusercontent.com/69875368/95610724-99736680-0a15-11eb-8bd6-b197ae87d869.png)

**Comment by shifucun** [comment]
This works now.
