### ISSUE TITLE
[Feedback] Consider per capita for COVID-19 deaths ranking page

### ISSUE THREAD

**Issue by tjann** [datacommonsorg/website#537]
### Feedback
I see the other rankings are per capita, which I think is more informative.
![image](https://user-images.githubusercontent.com/18621425/95628593-37295e80-0a33-11eb-93e5-bae9015e9009.png)

**Comment by beets** [comment]
this wasn't available before, and we can check if it'll work post @pradh 's fixes

**Comment by beets** [comment]
Closing this for now, since we aren't linking to it directly from the place explorer page (but will link to per capita, as appropriate for each stat var from the chart)
