### ISSUE TITLE
International rankings

### ISSUE THREAD

**Issue by rvguha** [datacommonsorg/website#546]
Reminder to make sure international rankings work

**Comment by beets** [comment]
some to check:
- [ ] https://staging.datacommons.org/ranking/Amount_EconomicActivity_GrossNationalIncome_PurchasingPowerParity_PerCapita/Country/asia?h=country%2FMYS&unit=%24
- [ ] https://staging.datacommons.org/ranking/LifeExpectancy_Person/Country?h=country%2FMYS
- [ ] https://staging.datacommons.org/ranking/Amount_Emissions_CarbonDioxide_PerCapita/Country/asia?h=country%2FCHN
- [ ] https://staging.datacommons.org/ranking/CumulativeCount_MedicalConditionIncident_COVID_19_PatientDeceased/Country?pc

**Comment by beets** [comment]
those are all fixed!
