### ISSUE TITLE
Timeline tool can not display on mobile

### ISSUE THREAD

**Issue by shifucun** [datacommonsorg/website#549]
Tested: Iphone 8+, chrome.

The entire page is covered up. The title section only partly shows up

**Comment by beets** [comment]
we should still figure out what to do with the actual page (previous fix only removes link to explore more on mobile)

**Comment by shifucun** [comment]
@beets Shall we move the chart column under stat var widget in mobile. Then all the tools are usable.

**Comment by beets** [comment]
We could also make the stat var widget as a popup or drawer that can be dismissed to show the charts. I suspect there might be other things to do as well, like how we display errors, and getting the charts to fit on the screen. But that's a first step :)
