### ISSUE TITLE
[BUG] Description of bug

### ISSUE THREAD

**Issue by IanCostello** [datacommonsorg/website#571]
### Describe the bug
The search feature for places returns the wrong city.

### To Reproduce
URL: https://datacommons.org/place?dcid=geoId%2F0649670
Browser: Firefox (N/A)

1. Go to https://datacommons.org/place?dcid=geoId%2F0649670
2. Click on Search -> Enter country, state, county, or city. 
3. Type Paris
4. Click on Paris, France
5. Notice that the link brings you to Paris, A Village in Mbua Tengah, Nduga, Papua. https://datacommons.org/place?dcid=wikidataId%2FQ25907009

### Expected behavior
Should take you to the city of Paris in France.

**Comment by beets** [comment]
Hi Ian! We just fixed this with a push last night.
