### ISSUE TITLE
[Feedback] Consider a way to fold opened up LHS Topics on place page

### ISSUE THREAD

**Issue by pradh** [datacommonsorg/website#605]
### Feedback
Consider a way to fold opened up LHS Topics on place page

### About
URL: https://datacommons.org/place/country/USA?topic=Economics

1. Go to https://datacommons.org/place/country/USA
2. Click on Economics
3. Suppose user now wants to navigate to the next Topic after Economics, user has to scroll down 5-6 pages to get to "Health" topic. (Or go back on browser or click Overview.)

**Comment by shifucun** [comment]
There is scroll bar in LHS menu now.
