### ISSUE TITLE
[Scatter2] enter on place search box should select first option

### ISSUE THREAD

**Issue by beets** [datacommonsorg/website#700]
### Feedback
Scatter 2: If I hit enter after typing in the place search box, we should automatically select the first option (place explorer does this).

![image](https://user-images.githubusercontent.com/6052978/101408806-cd41ff80-3891-11eb-9a94-2542b481bf6d.png)

**Comment by tjann** [comment]
@beets did you change your mind on https://github.com/datacommonsorg/website/issues/411 ?

**Comment by beets** [comment]
Yes, I did... And we implemented it in the place explorer
