### ISSUE TITLE
[Scatter2] clicking on "scatter2" in the header bar should clear options

### ISSUE THREAD

**Issue by beets** [datacommonsorg/website#704]
### Feedback
Clicking on "Scatter2" in the header bar should reset all options and clear the URL

To reproduce:
1. Click https://staging.datacommons.org/tools/scatter2#x%3D%7B%22statVar%22%3A%7B%7D%2C%22name%22%3A%22%22%2C%22data%22%3A%5B%5D%2C%22populations%22%3A%5B%5D%2C%22log%22%3Afalse%2C%22perCapita%22%3Afalse%7D%26y%3D%7B%22statVar%22%3A%7B%7D%2C%22name%22%3A%22%22%2C%22data%22%3A%5B%5D%2C%22populations%22%3A%5B%5D%2C%22log%22%3Afalse%2C%22perCapita%22%3Afalse%7D%26place%3D%7B%22enclosingPlace%22%3A%7B%22name%22%3A%22%22%2C%22dcid%22%3A%22%22%7D%2C%22enclosedPlaceType%22%3A%22%22%2C%22enclosedPlaces%22%3A%5B%5D%2C%22lowerBound%22%3A0%2C%22upperBound%22%3A10000000000%7D
1. Click Scatter2
--> expect the same state as navigating directly to staging.datacommons.org/tools/scatter2

(in fact, manually clearing the URL field doesn't reset either, and the options are added back to the URL)

**Comment by shifucun** [comment]
Now most params are cleared except for "&qd=0&ld=0"
