### ISSUE TITLE
[place] export link broken for non-latin languages

### ISSUE THREAD

**Issue by beets** [datacommonsorg/website#782]
on place pages with non-latin languages, e.g. in russian, the export link is broken:

Uncaught DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.

**Comment by shifucun** [comment]
Is there an example link? This does seem working now.

**Comment by beets** [comment]
I've fixed it but forgot to close this bug -- thanks for checking!
