### ISSUE TITLE
Better UI treatment for "per capita" option

### ISSUE THREAD

**Issue by shifucun** [datacommonsorg/website#841]
"per capita" is a not an accurate statement for cases like "positive covid test / total covid test". These are things we could do to improve it:

* Adjust the wording when denominator is not "Count_Person" and show explicitly what denominator is used.
* Allow user to pick arbitrary denominator like scatter plot (this is a larger change).

**Comment by beets** [comment]
map has this option now, but we need this for scatter & timeline

**Comment by beets** [comment]
it's been fixed, and we call this "ratio" now. though we have to filter when we show this..
