### ISSUE TITLE
Example issue

### ISSUE THREAD

**Issue by beets** [datacommonsorg/website#85]
Issue description:

What was expected:

How to reproduce:
- URL
- browser

Screenshot of the problem, if relevant:
[ copy/pasting screenshots from the clipboard into this form works! ]

**Comment by shifucun** [comment]
Maybe try the issue template like this: https://github.com/datacommonsorg/api-python/tree/master/.github/ISSUE_TEMPLATE

**Comment by beets** [comment]
Here's a sample report. @shifucun good idea, I'll make a template

Issue description:
- Overflow issue in the scatter tool

What was expected:
- UI elements stay contained to the main area
- PV tree menu should disappear, or overlap to give more space to the main chart drawing area

How to reproduce:
- Shrink the window 617x752 px
- URL - https://staging.datacommons.org/tools/scatter
- browser - chrome / mac osx

Screenshot of the problem, if relevant:
![image](https://user-images.githubusercontent.com/6052978/87699210-6472b300-c749-11ea-94e2-91f6aa00084f.png)

**Comment by beets** [comment]
> Maybe try the issue template like this: https://github.com/datacommonsorg/api-python/tree/master/.github/ISSUE_TEMPLATE

Added these to a template!
