### ISSUE TITLE
[BUG] DCID's for genomes missing from search

### ISSUE THREAD

**Issue by beets** [datacommonsorg/website#92]
### Describe the bug
Missing results for ENCODE related searches.

@spiekos could you add some examples here that don't work?

**Comment by spiekos** [comment]
Search on the dcid no longer works. This leads to no results being returned when you search for things like:
CHEMBL102202
TP63
ChemicalCompound

These previously would return the correct nodes under the old method in which the search operated only on the name property of entities.

**Comment by beets** [comment]
@spiekos the old search functionality will be available again at datacommons.org/search_dc after our next push to prod. Sorry for the trouble!
