### ISSUE TITLE
[BUG] Timeline sidebar expand carrot occasionally missing

### ISSUE THREAD

**Issue by tjann** [datacommonsorg/website#94]
### Describe the bug
On Timeline, I found some carrots missing: 
### To Reproduce
URL: https://staging.datacommons.org/tools/timeline#&place=geoId/0654092,geoId/06059&ptpv=Person,percent,healthOutcome,Diabetes,age,Years18Onwards__Person,percent,healthOutcome,Diabetes,gender,Female,age,Years20Onwards__Person,percent,healthOutcome,Diabetes,gender,Male,age,Years20Onwards

### Expected behavior
Always have carrots to show expand feature.

### Screenshots
![image](https://user-images.githubusercontent.com/18621425/87713858-bcb4af80-c75f-11ea-858b-51633c7585a0.png)

![image](https://user-images.githubusercontent.com/18621425/87713832-b3c3de00-c75f-11ea-8ea2-1b506973d7ab.png)

### Additional context
Scatter seems to be fine (but is it intentionally missing disasters?)

**Comment by beets** [comment]
@qlj-lijuan could you take a quick look at this - would be great to patch in a fix if it's simple.

**Comment by qlj-lijuan** [comment]
The image is not changed to the light one. I'll sent a PR to fix it.
